### ISSUE TITLE
Customer shared for missing content on WF page

### ISSUE THREAD

**Issue by ktayloradbe** [AdobeDocs/workfront.en#10]
Issue in ./help/quicksilver/workfront-goals/goal-alignment/align-goals-by-connecting-them.md

From a Google customer:
I'm working on documenting Goals for our Googlers and noticed [that this page ](https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-goals/goal-alignment/align-goals-by-connecting-them.html?lang=en#)seems to be missing the 1st of the two approaches to connecting goals. 

It mentions 2 approaches - 1 being to connect the two goals.  I had a user bring to my attention that it's not clear how this is done with the information on this page.

Is this page correct or missing something?

**Comment by ktayloradbe** [comment]
Teale says you can feel free to contact them if the author would like more detail
Teale McCleaf  | PMAT Workfront SME | [teale@google.com](mailto:teale@google.com) | 	 | [240-446-8080|tel:(240)446-8080]

**Comment by alinaw-adobe** [comment]
@ktayloradbe , I answered this issue a while back, but I can't remember whether it was in Jira or in Slack (I think it was Jira). At Any rate, making the same comment here to close this issue: the information in this article is complete - please see below. The article illustrates one way of aligning goals, the second way is a link to another article, so users will need to use both articles to find the relevant and complete information. 

This is the excerpt in the article: 

There are two approaches to connecting goals in Adobe Workfront Goals:

You can create alignment between goals by connecting goals to one another. This is a bottom-up approach to aligning goals.

You can manually align two goals or you can convert results and activities of an existing goal to another goal. The converted result or activity becomes the child goal of the original goal. This is a top-down approach to aligning goals.

This article describes how you can align goals to one another by connecting them. For information about aligning goals by converting results and activities to goals, see [Align goals by converting results and activities to goals](https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-goals/goal-alignment/align-goals-by-converting-results-activities.html?lang=en).

Hope this helps! Thank you! 
Alina Wilson
