### ISSUE TITLE
Download links need to be updated

### ISSUE THREAD

**Issue by jersnow21** [AdobeDocs/workfront.en#13]
Issue in ./help/quicksilver/administration-and-setup/manage-workfront/configure-proofing/install-desktop-proofing-viewer-org.md

The links to download the Desktop viewer are outdated and no longer work. They need to be replaced. The downloads links work in the [Install the Desktop Proofing Viewer | Adobe Workfront](https://experienceleague.adobe.com/docs/workfront/using/review-and-approve-work/proofing/use-the-desktop-proofing-viewer/installing-desktop-proofing-viewer.html?lang=en) article if that is a helpful reference. Thanks!

**Comment by cchristensen23** [comment]
The links have been replaced and are live on the help site.
