### ISSUE TITLE
Incorrect Syntax for SUBSTR Function

### ISSUE THREAD

**Issue by ehoffman98** [AdobeDocs/workfront.en#14]
Issue in ./help/quicksilver/reports-and-dashboards/reports/calc-cstm-data-reports/calculated-data-expressions.md

On [this article](https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/calculated-custom-data/calculated-data-expressions.html#text-calculated-custom-fields), the example syntax for the SUBSTR function is the following:
`SUBSTR({string}, number of start position, length of string)`

This is incorrect; the 3rd condition is not the length of the string, it's the number of end position. It should be updated to the following:
`SUBSTR({string}, number of start position, number of end position)`

**Comment by nwilliams-wf** [comment]
Hi @ehoffman98,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/calculated-custom-data/calculated-data-expressions.html#text-calculated-custom-fields), you wrote:

> This is incorrect; the 3rd condition is not the length of the string, it's the number of end position. It should be updated to the following:
> SUBSTR({string}, number of start position, number of end position)

As suggested, I have edited the article to correctly explain that the third argument of the SUBSTR function is the ending index number for the desired substring, not its length.

Thanks for helping to improve Workfront documentation!
