### ISSUE TITLE
Article feedback

### ISSUE THREAD

**Issue by nathanjohnso** [AdobeDocs/workfront.en#16]
Issue in ./help/quicksilver/reports-and-dashboards/reports/text-mode/edit-text-mode-in-filter.md

I think it would be very helpful to have this article updated to include reference to this kind of text mode filter found in this article: https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/custom-view-samples/filter-items-by-comparing-two-fields.html?lang=en

A lot of users do not know that this is an option and it would be helpful to at least link to or include this as a type of filter and how to edit it.

**Comment by alinaw-adobe** [comment]
I have added a link to the Filter section in this article: [Samples of custom filters](https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/custom-view-samples/custom-view-filter-grouping-samples.html?lang=en#:~:text=personal%20time%20off-,Samples%20of%20custom%20filters,-Filter%3A%20display%20incomplete) 
It should be live sometime today. 
Thank you!
