### ISSUE TITLE
getApiKey - wrong content-type?

### ISSUE THREAD

**Issue by ABC-LG** [AdobeDocs/workfront.en#17]
Issue in ./help/quicksilver/wf-api/general/event-subs-api.md

When trying to fetch the API key using the recommended way via `<hostname>/USER?action=getApiKey&username=<username>&password=<password>`, I do get the error message *Updates should be either a JSON list or map* unless I change the header's `Content-type` to `text/html`.

**Comment by rebeccas-workfront** [comment]
Hi,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-api/event-subscriptions/event-subs-api.html?lang=en), you wrote:

When trying to fetch the API key using the recommended way via <hostname>/USER?action=getApiKey&username=<username>&password=<password>, I do get the error message Updates should be either a JSON list or map unless I change the header's Content-type to text/html.

Thank you for bringing this to our attention. I tested that call and had the same experience as you, so I've gone ahead and updated that article. 

Thanks for helping to improve the Workfront documentation!
