### ISSUE TITLE
Reference in Article does not exist - broken link and no instructions

### ISSUE THREAD

**Issue by CianOB** [AdobeDocs/workfront.en#19]
Issue in ./help/quicksilver/workfront-fusion/apps-and-their-modules/workfront-proof-modules.md

Note the paragraph below references 'build' and links to 'build' in "this article" - but there is no 'build' section

<html>
<body>

Proof Type | Specify whether you want the proof that is created to have a basic workflow or an Automated Workflow.Then fill out the fields that display for the proof type you chose. For example, if you chose Automated Workflow, fill out the Workflow Stages field to configure the stages.You can use output from the Build module here if you include and run that module earlier in the scenario. For more information, see Build in this article.
-- | --

</body>
</html>Proof Type	
Specify whether you want the proof that is created to have a basic workflow or an Automated Workflow.

Then fill out the fields that display for the proof type you chose. For example, if you chose Automated Workflow, fill out the Workflow Stages field to configure the stages.

You can use output from the Build module here if you include and run that module earlier in the scenario. For more information, see [Build](https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/workfront-proof-modules.html?lang=en#build) in this article.

**Comment by rebeccas-workfront** [comment]
Hi,

Regarding this page of the Workfront documentation [(https://support.workfront.com/hc/en-us/articles/360007108774](https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/workfront-proof-modules.html?lang=en)), you wrote:

"Note the paragraph below references 'build' and links to 'build' in 'this article' - but there is no 'build' section."

Thank you for pointing that out. I've removed the confusing reference.

Thanks for helping to improve the Workfront documentation!
