### ISSUE TITLE
Documentation Suggestion for Experience League Article, Add or edit an image or other asset widget in a custom form

### ISSUE THREAD

**Issue by luiswf** [AdobeDocs/workfront.en#20]
Issue in ./help/quicksilver/administration-and-setup/customize-workfront/create-manage-custom-forms/add-widget-or-edit-its-properties-in-a-custom-form.md

Hey team, this is Luis Ramirez from the Assigned Support Engineering team at Adobe Workfront. I wanted to suggest adding a statement on Experience League article, Add or edit an image or other asset widget in a custom form regarding the ability to not add URL of images that are hosted under private links. Something like ensuring the link of the images being public would allow our customers to be aware of the URLs they are attempting to use when using this functionality. Currently, the article does not state anything regarding it, and we are receiving questions on why some links are invalid. 

Please feel free to reach out to me with any questions on Slack @ Luis Ramirez or via email, luisr@adobe.com 

Thank you for your assistance.

**Comment by lmileusnich** [comment]
Courtney closed this issue in Hub on 2/27/23 and replied to the requestor there.
