### ISSUE TITLE
Instruction does not exist

### ISSUE THREAD

**Issue by CianOB** [AdobeDocs/workfront.en#21]
Issue in ./help/quicksilver/workfront-fusion/scenarios/templates/fusion-templates-adminstration.md

I am trying to find out how to clone a scenario as a template

At the bottom of this page, there is a reference to 'cloning' a scenario as a template', it links to another page, but there is no instruction on that page - where is the location of the instruction for 'Cloning a scenario as a template' please?

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the Workfront documentation [(https://support.workfront.com/hc/en-us/articles/36000710877](https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-fusion/scenarios-in-fusion/fusion-scenario-templates/fusion-templates-adminstration.html?lang=en)), you wrote:

"I am trying to find out how to clone a scenario as a template. At the bottom of this page, there is a reference to 'cloning' a scenario as a template', it links to another page, but there is no instruction on that page - where is the location of the instruction for 'Cloning a scenario as a template' please?"

Thank you for pointing out this oversight. I've added a section to the "Create a template" page, and updated the link at the bottom of the page you cited. If you want to go directly to the new section, the link is:

https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-fusion/scenarios-in-fusion/fusion-scenario-templates/create-new-fusion-templates.html?lang=en#create-a-template-from-a-scenario

Thanks for helping to improve the Workfront documentation!
