### ISSUE TITLE
Hi i need help deleting a comment

### ISSUE THREAD

**Issue by jordanorris** [AdobeDocs/workfront.en#24]
Issue in ./help/quicksilver/home.md

The one at 9 am please help!!

**Comment by alinaw-adobe** [comment]
@jordanorris , where is this comment? Are you referring to a comment you entered on Experience League? Thanks!

**Comment by jordanorris** [comment]
No it's on workfront

**Comment by alinaw-adobe** [comment]
Ah, I see. If the comment is yours, you should be able to delete it unless your system administrator prevents you from doing so in your environment. 
This queue is only to report feedback for the Adobe Experience League articles. We do not have access to Workfront environments. 
If you have more questions and you want to call our Support team, please use this article (https://experienceleague.adobe.com/docs/workfront/using/basics/tips-tricks-for-basics/contact-customer-support.html?lang=en) to learn how to do that. 
Thanks!
