### ISSUE TITLE
Please review role access

### ISSUE THREAD

**Issue by HeatherKulbacki** [AdobeDocs/workfront.en#25]
Issue in ./help/quicksilver/workfront-fusion/organizations/organization-roles.md

according to this page, in the Scenarios table it looks like Members cannot Add/Delete/Edit scenarios. But I am a **member** of both an organization and a team in Fusion and and can do all those things. Same for Webhooks. I can probably do the same for the other objects, but I haven't tried.
I suggest a review of all Fusion access levels and what they can/cannot do.

**Comment by rebeccas-workfront** [comment]
Hello!

Thank you for pointing this out. I've reached out to the engineering team and will update the article as soon as I've pinned things down.

Thanks for helping to improve the Workfront documentation!

**Comment by rebeccas-workfront** [comment]
Hi!

Regarding this page of the Workfront documentation:

https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-fusion/organizations-in-fusion/organization-roles.html

you wrote:

"According to this page, in the Scenarios table it looks like Members cannot Add/Delete/Edit scenarios. But I am a member of both an organization and a team in Fusion and and can do all those things. Same for Webhooks. I can probably do the same for the other objects, but I haven't tried.
I suggest a review of all Fusion access levels and what they can/cannot do."

I've reviewed all of the role abilities with the engineering team, and have updated the article to accurately reflect team and organization roles.

Thanks again for helping improve the Workfront documentation!
