### ISSUE TITLE
Incorrect url for api-unsupported

### ISSUE THREAD

**Issue by snoopen** [AdobeDocs/workfront.en#28]
Issue in ./help/quicksilver/wf-api/api/deprecation-api-internal.md

The /api/ part does not work for api-unsupported in my testing. What did work was:

`https://<domainname>.my.workfront.com/attask/api-unsupported/proj/4c70...`

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-api/api-notes/deprecation-api-internal.html), you wrote:

"The /api/ part does not work for api-unsupported in my testing."

Thank you for bringing this to our attention. I've replaced the example text, and added a note to point out that the /api/ section is missing. 

Thanks for helping to improve the Workfront documentation!
