### ISSUE TITLE
Please fix screenshot size/resolution

### ISSUE THREAD

**Issue by sniemetz** [AdobeDocs/workfront.en#29]
Issue in ./help/quicksilver/manage-work/tasks/task-constraints/latest-available-time.md

Throughout your docs, the screenshots are low-res and no larger view is available. Makes them useless. 

Please allow me to view a larger version by clicking the embedded screenshot (like any other CMS does these days)

screenshot at 175%

![image](https://github.com/AdobeDocs/workfront.en/assets/4804028/0557d9e1-63ed-4d5f-9de6-ba3fccf77d86)

**Comment by alinaw-adobe** [comment]
I have uploaded a new image. Thanks for letting us know about this. Please let us know every time you find a low-resolution picture. We are working to correct this, but we might not be aware of all the instances. Thanks, again! 
https://experienceleague.adobe.com/docs/workfront/using/manage-work/tasks/task-constraints/latest-available-time.html?lang=en
