### ISSUE TITLE
Section "Using the Count Filter" is very wrong

### ISSUE THREAD

**Issue by davidclp1** [AdobeDocs/workfront.en#30]
Pretty much the whole "Count" section is wrong (heading included).  Please see the screenshot attached for my comments.

If you'd like me to review again after a revised version is drafted I'd be happy to.

Thank you

Regards, David.

![2024-01-16_23-37-57](https://github.com/AdobeDocs/workfront.en/assets/156831812/1e2e5c67-d3e7-496d-b4d9-e80ddec0578e)

**Comment by alinaw-adobe** [comment]
@rebeccas-workfront , I believe this is the article: https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-api/api-general-information/api-basics.html?lang=en 
Thanks!

**Comment by davidclp1** [comment]
Yes, that's the one.  I clicked the Report an Issue button at the bottom of this page but I'm guessing it didn't give you the URL.

Thank you for looking into it.

Regards, David

**Comment by rebeccas-workfront** [comment]
Hi David,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/adobe-workfront-api/api-general-information/api-basics.html?lang=en), you wrote:

"Pretty much the whole "Count" section is wrong (heading included). Please see the screenshot attached for my comments."

Thank you for bringing this to our attention. I've updated the article to reflect what you pointed out. The changes are live online now.

Thanks for helping to improve the Workfront documentation!

-Rebecca

**Comment by davidclp1** [comment]
Thank you Rebecca - the wording is perfect now!  Great job.

Regards,


David Cornwell

Senior Integrations Architect

E.

***@***.***

W.

leappoint.com<http://www.leappoint.com>

[https://signaturehound.com/api/v1/file/101tmrnldu6ojyg]<http://www.leappoint.com>

[https://signaturehound.com/api/v1/png/linkedin/round-outlined/000000.png]<https://www.linkedin.com/company/leappoint-llc/>

[https://signaturehound.com/api/v1/png/twitter/round-outlined/000000.png]<https://twitter.com/leappointllc>

[https://signaturehound.com/api/v1/png/facebook/round-outlined/000000.png]<https://www.facebook.com/LeapPoint>

[https://signaturehound.com/api/v1/png/instagram/round-outlined/000000.png]<https://www.instagram.com/leappoint>

[https://signaturehound.com/api/v1/png/youtube/round-outlined/000000.png]<https://www.youtube.com/channel/UCz_rJxXkbTiF49yGVeKbktA/featured?themeRefresh=1>

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

Book time to meet with me ***@***.***?anonymous&ep=pcard>

________________________________
