### ISSUE TITLE
Documentation does not match banner on Sandbox page

### ISSUE THREAD

**Issue by HeatherKulbacki** [AdobeDocs/workfront.en#31]
Issue in ./help/quicksilver/administration-and-setup/set-up-workfront/workfront-testing-environments/wf-custom-refresh-sandbox-environment.md

documentation indicates: The scheduled refresh occurs at 12:00 AM on the given date, based on the timezone of the user that submitted the request.
Yet when we schedule a refresh of our sandboxes (currently refreshing SB02 more than SB01), the banner always indicates "(Mountain Time)" regardless of who schedules the refresh or what time zone they are in.

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the customer documentation (https://experienceleague.adobe.com/docs/workfront/using/administration-and-setup/set-up-wf/testing-environments/wf-custom-refresh-sandbox-environment.html), you wrote:

"Documentation indicates: The scheduled refresh occurs at 12:00 AM on the given date, based on the timezone of the user that submitted the request. Yet when we schedule a refresh of our sandboxes (currently refreshing SB02 more than SB01), the banner always indicates "(Mountain Time)" regardless of who schedules the refresh or what time zone they are in."

Thank you for pointing this out. I contacted the team to find out what was accurate, and have updated the documentation to reflect their response. I will continue working with them to update the banner. 

Thank you for helping to improve the Workfront documentation!
