### ISSUE TITLE
Missing error message

### ISSUE THREAD

**Issue by purdueboiler1987** [AdobeDocs/workfront.en#32]
Issue in ./help/quicksilver/administration-and-setup/tips-tricks-and-troubleshooting/error-auto-provisioned-user-cant-log-in.md

The first sentence is "When an auto-provisioned user tries to log in for the first time, they receive the following error:

"

but the error isn't displayed.

**Comment by rebeccas-workfront** [comment]
Hello,



Regarding this page of the Workfront documentation (https://experienceleague.corp.adobe.com/docs/workfront/using/administration-and-setup/admin-setup-tips/error-auto-provisioned-user-cant-log-in.html), you wrote:



"The first sentence is 'When an auto-provisioned user tries to log in for the first time, they receive the following error:', but the error isn't displayed."



Thank you for pointing this out. I got in touch with the team, and they were able to provide me with the error. I've added it to the article. Searching for error messages in the documentation is a good way for users to find out what's going on, and I appreciate you letting us know about the missing message.



Thanks for helping to improve the Workfront documentation!
