### ISSUE TITLE
Make Diagrams Larger

### ISSUE THREAD

**Issue by purdueboiler1987** [AdobeDocs/workfront.en#33]
Issue in ./help/quicksilver/workfront-proof/wp-getstarted/workflow-examples/workflow-examples.md

In the 4 documents linked here, there are diagrams that show the proofing process.  It would be nice to make these larger so people can actually see what is being explained.

**Comment by cchristensen23** [comment]
Thank you for the request. I updated the screenshots when this request came in but failed to update and close the ticket.
