### ISSUE TITLE
Update Marketplace link in this Workfront article

### ISSUE THREAD

**Issue by blayneyk** [AdobeDocs/workfront.en#36]
Issue in ./help/quicksilver/administration-and-setup/configure-integrations/workfront-integrations-1.md

Hi there - I am on the DX Technology Partner Program team at Adobe. Are we able to update the following copy in the above article? The Workfront Marketplace link does not direct to a marketplace. Please update that link as well to direct to the Exchange Marketplace (filtered by Workfront integrations).

Original: "Examples of existing partner offerings include integrations with Salesforce.com, Oracle Responsys, and Microsoft Visual Studio. For more information about these and other partner integrations, see the [Workfront Marketplace](https://www.workfront.com/enterprise/marketplace/apps/)."

Revised: Workfront has many partner integrations that enrich your Workfront experience. Examples of existing partner offerings include integrations with Claravine, RWS Group, and more. For more information about these and other partner integrations, see the [Exchange Marketplace](https://exchange.adobe.com/apps/browse/ec?page=1&partnerLevel=All&product=WRKFRNT&sort=RELEVANCE).

Thank you!

**Comment by rebeccas-workfront** [comment]
Hello,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/en/docs/workfront/using/administration-and-setup/configure-integrations/workfront-integrations-1), you wrote:

"Hi there - I am on the DX Technology Partner Program team at Adobe. Are we able to update the following copy in the above article? The Workfront Marketplace link does not direct to a marketplace. Please update that link as well to direct to the Exchange Marketplace (filtered by Workfront integrations)."

Thank you for pointing this out! I've made the changes you suggested, and linked it to the filtered page you provided. The changes will be published online overnight.

Thanks for helping to improve the Workfront documentation!
