### ISSUE TITLE
Update Task Duration

### ISSUE THREAD

**Issue by chefness** [AdobeDocs/workfront.en#37]
Hi there,
I have some edit feedback for: 
help/quicksilver/manage-work/tasks/taskdurtn/task-duration-and-duration-type.md

I saw that 'mo' is recognised as month, as well as 'T'. 
Please feel free to add that additional option in the documentation too.

I wasn't sure how else to suggest an edit, as it was asking me to fork the repository, which I didn't want to get into.

Thanks!

**Comment by alinaw-adobe** [comment]
Hello. Thanks so much for submitting this improvement. 
I confirmed this is indeed the case, and I have made the addition for "months". 
Thanks, again, and this is a fine way to submit feedback.
