### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by hensleyUX** [AdobeDocs/workfront.en#38]
Issue in ./help/quicksilver/administration-and-setup/manage-workfront/configure-proofing/create-manage-automated-workflow-templates.md

"sage", should be "stage"

![Screenshot 2024-09-24 at 10 22 03 AM](https://github.com/user-attachments/assets/db29f47f-916b-4256-ada9-d7258565e374)

**Comment by cchristensen23** [comment]
Thanks for letting us know! I have corrected this typo. The changes will be live on Experience League by the end of the day.
