### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by cverges-medallia** [AdobeDocs/workfront.en#39]
Issue in ./help/quicksilver/workfront-fusion/apps-and-their-modules/netsuite.md

[Create a connection to NetSuite in a Workfront Fusion NetSuite module](https://experienceleague.adobe.com/en/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/netsuite#create-a-connection-to-netsuite-in-a-workfront-fusion-netsuite-module)

That link doesn't appear to work when I click it.  Using Chrome latest on a Mac.

**Comment by rebeccas-workfront** [comment]
Hello!

Regarding this page of the Workfront documentation [[insert link to page where the comment was made](https://experienceleague.adobe.com/en/docs/workfront/using/adobe-workfront-fusion/fusion-apps-and-modules/netsuite)], you wrote:

[That link doesn't appear to work when I click it. Using Chrome latest on a Mac.]

Thank you for pointing this out. I've fixed it, and the changes should be online in the next day or so.

Thanks for helping to improve the Workfront documentation!
