### ISSUE TITLE
No matter how hard I try, the valueexpression just can't be formatted. 

### ISSUE THREAD

**Issue by HerWong80** [AdobeDocs/workfront.en#5]
Issue in ./help/quicksilver/reports-and-dashboards/reports/text-mode/use-conditional-formatting-text-mode.md

**Comment by nwilliams-wf** [comment]
Hi @HerWong80 ,

Regarding this page of the Workfront documentation (https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/text-mode/use-conditional-formatting-text-mode.html?lang=en), you wrote:

> No matter how hard I try, the valueexpression just can't be formatted.

In textmode, `valueexpression` cannot be conditionally formatted at all, and you'll instead need to use a Calculated Custom Field as described in the referenced article. For standard formatting, ensure that the syntax surrounding your `valueexpression` is as outlined in this article: https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/text-mode/text-mode-syntax-overview.html?lang=en#valueexpression-syntax-overview-for-views-and-groupings. For more specific information, please reach out to Adobe Workfront support with details about the formatting you are trying to achieve. 

Thank you for commenting on Workfront documentation.
