### ISSUE TITLE
Workkfront Timesheets view comment box no given focus for user input

### ISSUE THREAD

**Issue by idesignstuff** [AdobeDocs/workfront.en#8]
Couldn't find a "Feedback" option inside of WF webapp, so I came here.

With the latest updates to the webapp for Workfront, when I use Timesheets (99.9% of my interaction with WF), every time I choose to add a comment (almost every time I use WF) to an entry of hours, the box pops up as expected, and I go type my comment, then look up to see it's blank. 🤬

**Please give the comment box focus** to accept the, um, comments the box is there to take.
Also, I'd like WF to remember the collapsed/expanded state of each job in my list. If I have a lot of jobs, most don't get hours often, so I want only the ones that do to be expanded.

Thanks for autosave!

**Comment by alinaw-adobe** [comment]
@idesignstuff , thanks so much for the feedback and I apologize for the long delay in responding. 

I have notified the team about what you're encountering - I know they have rolled out improvements around timesheets lately and they continue to work more to improve the experience. 
Please also log a ticket with our Support team when you see anything not working right. Those will get the team's attention in a timely fashion. 
I will close this issue for now, but please let us know if you see anything in the documentation that needs to be updated. I promise that the long delay in responding won't happen in the future. Again, I apologize for this. 

Alina
