### ISSUE TITLE
Needs an Update - Uses old terminology and excludes new capabilities 

### ISSUE THREAD

**Issue by CianOB** [AdobeDocs/workfront.en#9]
Issue in ./help/quicksilver/people-teams-and-groups/work-with-groups-and-teams/understanding-differences-and-similarities-between-groups-and-teams.md

we noticed, in conversation today, that you can filter for groups in the Workload Balancer (says planner on this list, we don't use planner anymore) - this says only teams are filterable in the resource planner.

**Comment by alinaw-adobe** [comment]
@CianOB , thanks so much for the feedback. I have updated the article with your information and the changes I made will be public sometime later today - October 12, 2022. 
I apologize for the delay in responding to your comment - this should not happen in the future. Please let us know how we can continue to update our documentation. 
Thanks. 
Alina
